security:
    encoders:
        FusionGrup\Bundle\RedBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        administrators:
            entity: { class: FusionGrupRedBundle:Usuario, property: mailUsu }
    firewalls:
        secured_area:
            pattern: ^/*
            anonymous: ~
            form_login: 
                login_path: /
                check_path: /login_check
                default_target_path: /inicio
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        # #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
